name: Chunked Push of GKI Source

on:
  workflow_dispatch:

jobs:
  sync-and-chunk-push:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl python3 unzip

    - name: Install repo tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

    - name: Initialize and sync GKI source
      run: |
        mkdir gki && cd gki
        repo init -u https://android.googlesource.com/kernel/manifest -b common-android12-5.10
        repo sync -c --no-tags --no-clone-bundle --optimized-fetch

    - name: Chunked Push to Your GitHub Repo
      env:
        GH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
      run: |
        set -e
        cd gki

        GIT_USER="zentrozx"
        TARGET_REPO="zentrozx/gki-builder"
        GIT_URL="https://${GIT_USER}:${GH_TOKEN}@github.com/${TARGET_REPO}.git"

        # Clone target repo to temp dir
        cd ..
        git clone "$GIT_URL" target-repo
        cd target-repo

        git config user.name "$GIT_USER"
        git config user.email "$GIT_USER@users.noreply.github.com"

        # Loop through top-level GKI folders and push them one by one
        for dir in ../gki/common/*; do
          dname=$(basename "$dir")
          echo "Adding $dname..."
          cp -r "$dir" ./

          git add "$dname"
          git commit -m "Add $dname from GKI source" || echo "Nothing to commit"
          git push origin main
        done